clear; close all;
addpath(genpath('helper_functions'));

% Define location of input file
% TODO: redo filenames to use fullfile()
input_directory = pwd;
input_filenames = {'kim possible/tuning_data_pressure_251126_15psi', ...
                        'kim possible/tuning_data_pressure_251126_20psi', ...
                        'kim possible/tuning_data_pressure_251126_30psi', ...
                        'kim possible/tuning_data_vent_251126_15psi', ...
                        'kim possible/tuning_data_vent_251126_20psi', ...
                        'kim possible/tuning_data_vent_251126_30psi_trial2', ...
                        'kim possible/secondary configuration/tuning_data_vent_251126_15psi', ...
                        'kim possible/secondary configuration/tuning_data_vent_251126_20psi', ...
                        'kim possible/secondary configuration/tuning_data_vent_251126_30psi', ...
                        'ron stoppable/tuning_data_pressure_251125_15psi', ...
                        'ron stoppable/tuning_data_pressure_251125_20psi', ...
                        'ron stoppable/tuning_data_pressure_251125_30psi', ...
                        'ron stoppable/tuning_data_vent_251125_15psi', ...
                        'ron stoppable/tuning_data_vent_251125_20psi', ...
                        'ron stoppable/tuning_data_vent_251125_30psi', ...
                        'ron stoppable/secondary configuration/tuning_data_vent_251126_15psi', ...
                        'ron stoppable/secondary configuration/tuning_data_vent_251126_20psi', ...
                        'ron stoppable/secondary configuration/tuning_data_vent_251126_30psi', ...
                        'ron stoppable/valve 02/tuning_data_pressure_251126_15psi', ...
                        'ron stoppable/valve 02/tuning_data_pressure_251126_20psi', ...
                        'ron stoppable/valve 02/tuning_data_pressure_251126_30psi', ...
                        'ron stoppable/valve 02/tuning_data_vent_251126_15psi', ...
                        'ron stoppable/valve 02/tuning_data_vent_251126_20psi', ...
                        'ron stoppable/valve 02/tuning_data_vent_251126_30psi', ...
                        'ron stoppable/valve 02/secondary configuration/tuning_data_vent_251126_15psi', ...
                        'ron stoppable/valve 02/secondary configuration/tuning_data_vent_251126_20psi', ...
                        'ron stoppable/valve 02/secondary configuration/tuning_data_vent_251126_30psi', ...
                        'ron stoppable/valve 02/upstream 45psi/tuning_data_pressure_251126_15psi', ...
                        'ron stoppable/valve 02/upstream 45psi/tuning_data_pressure_251126_20psi', ...
                        'ron stoppable/valve 02/upstream 45psi/tuning_data_pressure_251126_30psi', ...
                        'ron stoppable/valve 02/upstream 45psi/tuning_data_vent_251126_15psi', ...
                        'ron stoppable/valve 02/upstream 45psi/tuning_data_vent_251126_20psi', ...
                        'ron stoppable/valve 02/upstream 45psi/tuning_data_vent_251126_30psi'};


% Define thresholds for determining when valve has started to open
% Thresholds defined as % of pressure change
pressure_thresholds = [0.05, 0.95];

% Define location for figure outputs
enable_save_figs = true;
fig_directory = fullfile(input_directory, 'figures');




% Define colors
plot_spec.colors.blue = [0, 129, 204] / 255;
plot_spec.colors.red = [201, 20, 23] / 255;
plot_spec.colors.navy = [0, 77, 128] / 255;

% Define plot specifications
plot_spec.plot_width_px = 3 * 400;
plot_spec.plot_height_px = 3 * 300;
improveFig = @(plot_width_px, plot_height_px) ...
    improveHangerFig (plot_width_px, plot_height_px);



%% Parse input file and plot this trial's data
num_files = length(input_filenames);
for file_index = 1:num_files

    % Get current filename and filepath
    temp_filename = input_filenames{file_index};
    temp_input_filepath = fullfile (input_directory, [temp_filename, '.txt']);

    % Parse data
    parsed_valve_data = parseValveData (temp_input_filepath, pressure_thresholds);

    % Generate and save figures
    figure_name = strrep(temp_filename, '/', ' - ');
    plotValveTrial (parsed_valve_data, figure_name, plot_spec)
    improveFig (plot_spec.plot_width_px, plot_spec.plot_height_px);
    saveOpenFigs(fig_directory, 'png');
    close all;

end
