function plotValveCalibrationCurves (parsed_valve_data, figure_name, plot_spec)

    figure ('Name', figure_name);
    t = tiledlayout(2, 2);

    num_trials = numel(parsed_valve_data);
    colors.pressure = linspace (0, 0.6, num_trials)' * [1,1,1];
    
    % Pressure vs. PWM value (raw)
    nexttile; hold on;
    for trial_index = 1:num_trials
        x_data = parsed_valve_data(trial_index).data(:, 1);
        y_data = parsed_valve_data(trial_index).data(:, 2);
        plot (x_data, y_data, '.-', ...
            'MarkerSize', 15, ...
            'LineWidth', 2, ...
            'Color', colors.pressure(trial_index, :));

        plot (x_data(parsed_valve_data(trial_index).pwm_limits(1)), ...
            y_data(parsed_valve_data(trial_index).pwm_limits(1)), ...
            '.', ...
            'MarkerSize', 20, ...
            'Color', plot_spec.colors.blue)
        xline(parsed_valve_data(trial_index).pwm_limits(1), ...
            '--', ...
            'LineWidth', 1, ...
            'Alpha', 1, ...
            'Color', plot_spec.colors.blue);

        plot (x_data(parsed_valve_data(trial_index).pwm_limits(2)), ...
            y_data(parsed_valve_data(trial_index).pwm_limits(2)), ...
            '.', ...
            'MarkerSize', 20, ...
            'Color', plot_spec.colors.navy)
        xline(parsed_valve_data(trial_index).pwm_limits(2), ...
            '--', ...
            'LineWidth', 1, ...
            'Alpha', 1, ...
            'Color', plot_spec.colors.navy);

    end
    xlabel ('PWM value [-]');
    ylabel ('Pressure [psi]');
    axis ([0, 255, 0, inf]);


    nexttile; hold on;
    for trial_index = 1:num_trials
        x_data = parsed_valve_data(trial_index).pwm_scaled;
        y_data = parsed_valve_data(trial_index).data(:, 2);
        plot (x_data, y_data, '.-', ...
            'MarkerSize', 15, ...
            'LineWidth', 2, ...
            'Color', colors.pressure(trial_index, :));

    end
    xline(0, ...
        '--', ...
        'LineWidth', 1, ...
        'Alpha', 1, ...
        'Color', plot_spec.colors.blue);
    xline(1, ...
        '--', ...
        'LineWidth', 1, ...
        'Alpha', 1., ...
        'Color', plot_spec.colors.blue);
    xlabel ('Controller signal');
    ylabel ('Pressure [psi]');
    axis([-3, 3, -inf, inf])



    nexttile; hold on;
    x_data = max([[parsed_valve_data.pressure_start_psi]; ...
        [parsed_valve_data.pressure_end_psi]]', [], 2);
    y_data = cell2mat({parsed_valve_data.pwm_limits}');
    plot (x_data, y_data(:, 1), ...
        '.--', ...
        'MarkerSize', 20, ...
        'LineWidth', 1, ...
        'Color', plot_spec.colors.blue);
    plot (x_data, y_data(:, 2), ...
        '.--', ...
        'MarkerSize', 20, ...
        'LineWidth', 1, ...
        'Color', plot_spec.colors.navy);

    xlabel ('Source pressure [psi]');
    ylabel ('PWM values [-]');
    axis ([12.5, 32.5, 100, 200]);
    legend ({'Minimum value', 'Maximum value'}, ...
        'Box', 'off', ...
        'Location', 'southeast');
 
    
    nexttile; hold on;
    for trial_index = 1:num_trials

        x_data = parsed_valve_data(trial_index).pwm_scaled;
        y_data = 100 * parsed_valve_data(trial_index).pressure_scaled;

        plot (x_data, y_data, '.-', ...
            'MarkerSize', 15, ...
            'LineWidth', 2, ...
            'Color', colors.pressure(trial_index, :));

        yline(100 * parsed_valve_data(trial_index).pressure_thresholds, ...
            '--', ...
            'LineWidth', 1, ...
            'Alpha', 1, ...
            'Color', plot_spec.colors.red);

        xline(0, ...
            '--', ...
            'LineWidth', 1, ...
            'Alpha', 1, ...
            'Color', plot_spec.colors.blue);
        xline(1, ...
            '--', ...
            'LineWidth', 1, ...
            'Alpha', 1, ...
            'Color', plot_spec.colors.navy);

        plot (x_data(parsed_valve_data(trial_index).pwm_limits(1)), ...
            y_data(parsed_valve_data(trial_index).pwm_limits(1)), ...
            '.', ...
            'MarkerSize', 20, ...
            'Color', plot_spec.colors.blue)
         plot (x_data(parsed_valve_data(trial_index).pwm_limits(2)), ...
            y_data(parsed_valve_data(trial_index).pwm_limits(2)), ...
            '.', ...
            'MarkerSize', 20, ...
            'Color', plot_spec.colors.navy)
    
    end

    xlabel ('Controller signal');
    ylabel ('Pressure [% of signal range]');
    axis([-3, 3, -10, 110])
    

end
