function plotValveTrial (parsed_valve_data, figure_name, plot_spec)

    figure ('Name', figure_name);
    t = tiledlayout(2, 2);
    
    % Pressure vs. PWM value (raw)
    nexttile;
    x_data = parsed_valve_data.data(:, 1);
    y_data = parsed_valve_data.data(:, 2);
    plot (x_data, y_data, '.-', ...
        'MarkerSize', 15, ...
        'LineWidth', 2, ...
        'Color', [0,0,0]);
    xlabel ('PWM value [-]');
    ylabel ('Pressure [psi]');
    axis ([0, 255, 0, inf]);
    
    nexttile; hold on;
    x_data = parsed_valve_data.data(:, 1);
    y_data = 100 * parsed_valve_data.pressure_scaled;
    plot (x_data, y_data, '.-', ...
        'MarkerSize', 15, ...
        'LineWidth', 2, ...
        'Color', [0,0,0]);
    yline(100 * parsed_valve_data.pressure_thresholds, ...
        '--', ...
        'LineWidth', 2, ...
        'Alpha', 0.5, ...
        'Color', plot_spec.colors.red);
    xline(parsed_valve_data.pwm_limits, ...
        '--', ...
        'LineWidth', 2, ...
        'Alpha', 0.5, ...
        'Color', plot_spec.colors.blue);
    plot (x_data(parsed_valve_data.pwm_limits), y_data(parsed_valve_data.pwm_limits), ...
        '.', ...
        'MarkerSize', 20, ...
        'Color', plot_spec.colors.blue)
    xlabel ('PWM value [-]');
    ylabel ('Pressure [% of signal range]');
    axis ([0, 255, -10, 110]);
    
    nexttile; hold on;
    x_data = parsed_valve_data.pwm_scaled;
    y_data = 100 * parsed_valve_data.pressure_scaled;
    plot (x_data, y_data, '.-', ...
        'MarkerSize', 15, ...
        'LineWidth', 2, ...
        'Color', [0,0,0]);
    yline(100 * parsed_valve_data.pressure_thresholds, ...
        '--', ...
        'LineWidth', 2, ...
        'Alpha', 0.5, ...
        'Color', plot_spec.colors.red);
    xline([0, 1], ...
        '--', ...
        'LineWidth', 2, ...
        'Alpha', 0.5, ...
        'Color', plot_spec.colors.blue);
    plot (x_data(parsed_valve_data.pwm_limits), y_data(parsed_valve_data.pwm_limits), ...
        '.', ...
        'MarkerSize', 20, ...
        'Color', plot_spec.colors.blue)
    xlabel ('Controller signal');
    ylabel ('Pressure [% of signal range]');
    axis([-3, 3, -10, 110])
    
    
    nexttile;
    display_text = {
        sprintf('Starting pressure: %.3g psi', parsed_valve_data.pressure_start_psi), ...
        sprintf('Final pressure: %.3g psi', parsed_valve_data.pressure_end_psi), ...
        sprintf('Pressure change: %.3g psi', abs(parsed_valve_data.pressure_end_psi - parsed_valve_data.pressure_start_psi)), ...
        sprintf('Pressure thresholds: [%d, %d] %%', 100 * parsed_valve_data.pressure_thresholds(1), 100 * parsed_valve_data.pressure_thresholds(2)), ...
        sprintf('PWM thresholds: [%d, %d]', parsed_valve_data.pwm_limits(1), parsed_valve_data.pwm_limits(2)) ...
        };
    text(0, 0.5, display_text, ...
        'Units', 'normalized', ... 
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle', ...
        'FontSize', 12, ...
        'FontName', 'Avenir');
    axis off;
    

end
